
matrix:
  include:
    - os: linux
      dist: trusty
      env: IRAFARCH=linux64 LINUXDIST=trusty
      addons:
        apt:
          packages:
            - flex-old
            - byacc
    - os: linux
      dist: precise
      env: IRAFARCH=linux64 LINUXDIST=precise
      addons:
        apt:
          packages:
            - flex-old
            - byacc
    - os: linux
      dist: trusty
      env: IRAFARCH=linux OS_VERS=trusty
      addons:
        apt:
          packages:
            - flex-old
            - byacc
            - gcc-multilib
            - libcurl4-gnutls-dev:i386
            - libncurses5-dev:i386
            - libexpat1-dev:i386
    - os: linux
      dist: precise
      env: IRAFARCH=linux OS_VERS=precise
      addons:
        apt:
          packages:
            - flex-old
            - byacc
            - gcc-multilib
            - libcurl4-gnutls-dev:i386
            - libncurses5-dev:i386
            - libexpat1-dev:i386
    - os: osx
      osx_image: xcode8.3
      env: IRAFARCH=macintel OS_VERS=sierra
    - os: osx
      osx_image: xcode7.3
      env: IRAFARCH=macintel OS_VERS=elcapitan
    - os: osx
      osx_image: xcode6.4
      env: IRAFARCH=macintel OS_VERS=yosemite
    - os: osx
      osx_image: xcode8.3
      env: IRAFARCH=macosx OS_VERS=sierra
    - os: osx
      osx_image: xcode7.3
      env: IRAFARCH=macosx OS_VERS=elcapitan
    - os: osx
      osx_image: xcode6.4
      env: IRAFARCH=macosx OS_VERS=yosemite


language: c

before_script:
  - build_tmp=`mktemp -d -t irafbuild.XXXXXXXXX`
  - ./install -v --term xterm --bindir $build_tmp/bin --cache $build_tmp/cache --imdir $build_tmp/imdir --root `pwd` < /dev/null || true
  - make ${IRAFARCH}
  - make sysgen

script:
  - source unix/hlib/setup.sh
  - ./test/run_tests
