matrix:
  include:
    - os: linux
      dist: trusty
      env: IRAFARCH=linux64 OS_VERS=trusty
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libexpat-dev
            - libreadline-dev
    - os: linux
      dist: precise
      env: IRAFARCH=linux64 OS_VERS=precise
      addons:
        apt:
          packages:
            - libreadline-dev
    - os: linux
      dist: trusty
      env: IRAFARCH=linux OS_VERS=trusty CARCH="-m32"
      addons:
        apt:
          packages:
            - gcc-multilib
            - libcurl4-openssl-dev:i386
            - libexpat-dev:i386
            - libreadline-dev:i386
    - os: linux
      dist: precise
      env: IRAFARCH=linux OS_VERS=precise CARCH="-m32"
      addons:
        apt:
          packages:
            - gcc-multilib
            - libcurl4-openssl-dev:i386
            - libexpat-dev:i386
            - libreadline-dev:i386
    - os: osx
      osx_image: xcode10
      env: IRAFARCH=macintel OS_VERS=highsierra TARFILE=iraf.macintel.tar.gz
    - os: osx
      osx_image: xcode6.4
      env: IRAFARCH=macintel OS_VERS=yosemite
    - os: osx
      osx_image: xcode9.4
      env: IRAFARCH=macosx OS_VERS=highsierra CARCH="-m32"
    - os: osx
      osx_image: xcode7.3
      env: IRAFARCH=macosx OS_VERS=elcapitan CARCH="-m32"

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install ccache; PATH=/usr/local/opt/ccache/libexec:$PATH ; fi

language: c

cache:
  ccache: true
  directories:
    - $HOME/.ccache

git:
  depth: 3

before_script:
  - build_tmp=$(mktemp -d -t irafbuild.XXXXXXXXX)
  - mkdir -p ${build_tmp}/bin
  - PATH=${build_tmp}/bin:$PATH
  - ./install --term xterm --bindir $build_tmp/bin --cache $build_tmp/cache --imdir $build_tmp/imdir --root $(pwd) < /dev/null || true
  - make ${IRAFARCH}
  - make sysgen

script:
  - ./test/run_tests

before_deploy:
 - git checkout unix/hlib/
 - tar --exclude ${TARFILE} -czf ${TARFILE} *
 - ls -l

deploy:
  provider: releases
  api_key:
    secure: dGZRYkRPIz1jcJa8CGBc54eyqUx+7x2yHoezF4IWnl83dU1NC95/zretldXuQ5SP4ksRGp+TMnsH1x8hvaC3qd9G2ZXYnsKTAfWvRThXZW1LA8B1kEZfLikz0rBs7bw7qQirpdy64S0VAooeav4sTF7CHdqXCjqgQNlD/FGDwYKLOxhUq30YBDeCYOMn/CvvumQmwhynd74eTueCykEGFcVJe8k08+AS3V8N4AhN6gger9W2bZVxhPPaxUx1qyHurDAj+fq89QtOHwh+sq7VK7hDMmB2mfQvfekesUb0WUWx5VoNhHb+NzCfOWgaw0VKSQYuFte6Wy4xTTpyPr0H4AO8kGWFIn9fF/F41mQB+EtFZk0Cf84+rHgzUKn2wxr0nQUGUEmbeUT+gdyC5myegc5E6FThnPmbsTX8sebDj5VJP1ptJgeStJA0mD2C+mU86dU/nzLVjm8YApj7vxzs3k02DUmfayCcnUbZ8byBtxL5or0Wu70YJdJ7K0YDb09ABKJm/7oGNZHt6aTef2yxb/2iick8EsQxehT4qaqAypVcPHyalL9CsjEjAKYygCkhh/seVyeT37WB54k8G4fDuGYKLhO5If/E6igaZECcQaff5RQkw1a10ZHuWfC4hHOOGrA2i/g+JhHAasofeoHNq4W6dp8ymfV2/HmIb6feC/k=
  file: ${TARFILE}
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    condition: ${TARFILE}
